import type { Dossier } from '../types/dossier';

export const PRESET_DOSSIERS: Dossier[] = [
  {
    id: 'target-morozov-01',
    fio: {
      last: 'Морозов',
      first: 'Александр',
      middle: 'Дмитриевич',
      full: 'Морозов Александр Дмитриевич',
    },
    aliases: ['ShadowWolf', 'morozov_vc', 'dark_nomad', 'AM_Alpha'],
    birthDate: '14.08.1989',
    birthPlace: 'г. Москва, РСФСР',
    age: 37,
    gender: 'Мужской',
    zodiac: 'Лев ♌',
    totemAnimal: 'Волк',
    totemTitle: 'Серый Волк Теневого Потока',
    threatLevel: 'CRITICAL',
    riskScore: 89,
    biometricMatchRate: 98.4,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    summary: 'Ключевой бенефициар нескольких теневых крипто-шлюзов и венчурных фондов в юрисдикциях ОАЭ и Сейшел. Фигурант закрытых оперативных баз финансового мониторинга. Активно использует скрытые протоколы связи и дроп-сервисы.',
    
    documents: [
      {
        type: 'Паспорт гражданина РФ',
        series: '4512',
        number: '883921',
        issueDate: '28.08.2009',
        issuedBy: 'ОВД Тверского района города Москвы',
        departmentCode: '770-021',
        status: 'Действителен',
        extra: {
          'Адрес регистрации': 'г. Москва, ул. Тверская, д. 19, кв. 84',
          'СНИЛС': '158-920-441 90',
          'ИНН': '771098451203',
        },
      },
      {
        type: 'Заграничный паспорт РФ',
        series: '75',
        number: '4820199',
        issueDate: '11.03.2021',
        issuedBy: 'ГУВМ МВД 77001',
        departmentCode: '77001',
        status: 'Действителен',
        extra: {
          'Действует до': '11.03.2031 (Биометрический 10 лет)',
          'Визы': 'ОАЭ (Resident ID), Шенген (Мульти Франция 5 лет), США B1/B2',
        },
      },
      {
        type: 'Водительское удостоверение',
        series: '9920',
        number: '419830',
        issueDate: '15.09.2017',
        issuedBy: 'ГИБДД 7712',
        departmentCode: '7712',
        status: 'Действителен',
        extra: {
          'Категории': 'B, B1, M, A',
          'Стаж с': '2007 г.',
        },
      },
      {
        type: 'СНИЛС',
        number: '158-920-441 90',
        issueDate: '12.04.2004',
        status: 'Действителен',
      },
      {
        type: 'ИНН Физического лица',
        number: '771098451203',
        issueDate: '19.05.2008',
        issuedBy: 'ИФНС России № 10 по г. Москве',
        status: 'Действителен',
      },
    ],

    telecom: [
      {
        number: '+7 (926) 840-19-22',
        operator: 'ПАО МегаФон',
        region: 'г. Москва и МО',
        imsi: '250028819401290',
        imei: '358941092834019 (iPhone 15 Pro Max Deep Blue)',
        period: '2021 — 2026 (Основной)',
        status: 'Активен',
        tags: ['Саша Морозов VC', 'Алекс Инвест Барвиха', 'Морозов Крипта Тверская', 'Александр Дмитриевич Т-Банк'],
        messengerStatus: { telegram: true, whatsapp: true, signal: true },
      },
      {
        number: '+7 (903) 711-40-55',
        operator: 'ПАО ВымпелКом (Билайн)',
        region: 'г. Москва',
        imsi: '250991409284102',
        imei: '869401928410294 (Google Pixel 8 Pro GrapheneOS)',
        period: '2023 — 2026 (Скрытый/Оперативный)',
        status: 'Активен',
        tags: ['Drop Secure AM', 'Технический Саша'],
        messengerStatus: { telegram: true, signal: true },
      },
      {
        number: '+971 50 491 8203',
        operator: 'e& (Etisalat UAE)',
        region: 'Dubai, UAE',
        imsi: '424029401928301',
        imei: '358941092834019',
        period: '2022 — 2026',
        status: 'Активен',
        tags: ['Alex Morozov Dubai Marina', 'Morozov VC UAE'],
        messengerStatus: { telegram: true, whatsapp: true },
      },
    ],

    telegram: {
      id: '491820491',
      username: 'morozov_vc',
      firstName: 'Alex',
      lastName: 'M.',
      phone: '+79268401922',
      bio: 'Venture & Digital Assets. DM only with intro.',
      leakedMessagesCount: 4280,
      groups: [
        'Crypto Whales Club CIS (Admin)',
        'Dubai Real Estate Investors VIP',
        'DeFi Architects Core',
        'Barvikha Owners Private Chat',
        'Moscow Alpha Syndicate',
      ],
      lastSeen: 'Сегодня в 04:12 (с IP в Дубае)',
    },

    emails: [
      'a.morozov@solaris-capital.io',
      'shadow_wolf89@protonmail.com (Связан с утечкой BreachForums)',
      'morozov.capital@gmail.com',
      'am_invest@icloud.com',
    ],

    socialLinks: [
      { platform: 'Telegram', url: 'https://t.me/morozov_vc', username: '@morozov_vc' },
      { platform: 'LinkedIn', url: 'https://linkedin.com/in/alex-morozov-vc', username: 'alex-morozov-vc' },
      { platform: 'GitHub', url: 'https://github.com/shadow-nomad-core', username: 'shadow-nomad-core' },
      { platform: 'Twitter/X', url: 'https://x.com/alex_morozov_89', username: '@alex_morozov_89' },
    ],

    ipAddresses: [
      { ip: '185.220.101.45', isp: 'M247 Ltd (Tor Exit / WireGuard)', city: 'Frankfurt, DE', lastSeen: '19.09.2026 23:40' },
      { ip: '94.204.71.18', isp: 'Du Telecommunications', city: 'Dubai, UAE', lastSeen: '20.09.2026 01:15' },
      { ip: '178.62.199.10', isp: 'DigitalOcean Cloud Proxy', city: 'Amsterdam, NL', lastSeen: '18.09.2026 14:02' },
      { ip: '212.45.12.89', isp: 'ПАО МТС (Домашний интернет МГТС GPON)', city: 'Москва, Тверская', lastSeen: '10.09.2026 18:22' },
    ],

    finances: {
      estimatedNetWorth: '₽ 840,000,000 (~$9.2M)',
      taxId: '771098451203',
      snils: '158-920-441 90',
      banks: [
        {
          bank: 'АО «Т-Банк» (Тинькофф Премиум)',
          accountMasked: '40817810****9921',
          currency: 'RUB',
          balanceEstimated: '₽ 34,250,000',
          openDate: '12.04.2016',
          status: 'Активен',
        },
        {
          bank: 'ПАО «Сбербанк» (СберПервый)',
          accountMasked: '40817810****4108',
          currency: 'RUB',
          balanceEstimated: '₽ 89,100,000',
          openDate: '09.11.2014',
          status: 'Активен',
        },
        {
          bank: 'Emirates NBD (Dubai)',
          accountMasked: 'AE480260****8912',
          currency: 'AED / USD',
          balanceEstimated: '$ 4,800,000',
          openDate: '18.06.2022',
          status: 'Активен',
        },
      ],
      crypto: [
        {
          network: 'Bitcoin (BTC)',
          address: 'bc1q9x8904zkj28y43lqpm848209aklsdfm89234k',
          balance: '64.82 BTC (~₽ 415M)',
          totalTx: 1420,
          lastActivity: '19.09.2026 21:05',
          riskCategory: 'Миксер/Darknet',
        },
        {
          network: 'Tether (USDT TRC20)',
          address: 'TX9kP28aBvM49LsQ881nZkaOpmx882JkpL',
          balance: '1,240,000 USDT',
          totalTx: 5890,
          lastActivity: '20.09.2026 00:32',
          riskCategory: 'P2P Офшор',
        },
        {
          network: 'Monero (XMR)',
          address: '888tNkZr4m8Y981Lkx2039kLspq981240Klsdf...',
          balance: '450.0 XMR (Конфиденциально)',
          totalTx: 312,
          lastActivity: '17.09.2026',
          riskCategory: 'Миксер/Darknet',
        },
      ],
      companies: [
        {
          name: 'ООО «СОЛАРИС ДИДЖИТАЛ КАПИТАЛ»',
          inn: '7703492810',
          ogrn: '1197746819201',
          role: 'Генеральный директор',
          revenueYear: '₽ 148,200,000 / год',
          status: 'Действующее',
          registrationDate: '14.10.2019',
        },
        {
          name: 'SOLARIS VENTURES FZ-LLC (Dubai DMCC)',
          inn: 'DMCC-894102',
          ogrn: 'UAE-REG-48192',
          role: 'Бенефициарный владелец',
          revenueYear: '$ 3,400,000 / год',
          status: 'Действующее',
          registrationDate: '22.03.2022',
        },
        {
          name: 'ИП Морозов Александр Дмитриевич',
          inn: '771098451203',
          ogrn: '318774600192834',
          role: 'ИП',
          revenueYear: '₽ 54,000,000 / год',
          status: 'Действующее',
          registrationDate: '11.02.2018',
        },
      ],
    },

    assets: {
      vehicles: [
        {
          brandModel: 'Porsche 911 GT3 RS (992)',
          plate: 'А777МР77',
          vin: 'WP0ZZZ99ZNS284910',
          year: 2023,
          color: 'Черный матовый / Червонное золото',
          stsNumber: '9948 291048',
          osagoNumber: 'ХХХ 0294819024 (Ингосстрах VIP)',
          finesCount: 14,
          finesSum: '₽ 28,500 (Оплачены)',
          registrationDate: '14.05.2023',
          status: 'В собственности',
        },
        {
          brandModel: 'Mercedes-Maybach GLS 600 4MATIC',
          plate: 'В001ВВ777',
          vin: 'WDC1679871A294819',
          year: 2022,
          color: 'Двухцветный Obsidian Black / Rubellite Red',
          stsNumber: '9934 819204',
          osagoNumber: 'ХХХ 0184920192 (АльфаСтрахование)',
          finesCount: 6,
          finesSum: '₽ 7,500 (Оплачены)',
          registrationDate: '02.09.2022',
          status: 'В собственности',
        },
      ],
      realEstate: [
        {
          type: 'Квартира',
          address: 'г. Москва, ул. Тверская, д. 19, кв. 84 (ЖК Тверская Плаза)',
          cadastralNumber: '77:01:0001045:1094',
          areaSqMeters: 184.5,
          estimatedPrice: '₽ 145,000,000',
          ownershipShare: '1/1 (Единоличная)',
          registrationDate: '18.11.2018',
          encumbrance: 'Без обременений',
        },
        {
          type: 'Загородный дом',
          address: 'Московская обл., Одинцовский р-н, пос. Барвиха, КП «Сады Майендорф», уч. 14',
          cadastralNumber: '50:20:0010482:481',
          areaSqMeters: 740.0,
          estimatedPrice: '₽ 390,000,000',
          ownershipShare: '1/1',
          registrationDate: '24.06.2021',
          encumbrance: 'Без обременений',
        },
        {
          type: 'Апартаменты',
          address: 'United Arab Emirates, Dubai, Dubai Marina, Princess Tower, Penthouse #8204',
          cadastralNumber: 'DXB-MARINA-88410',
          areaSqMeters: 310.0,
          estimatedPrice: '$ 2,400,000 (~₽ 220,000,000)',
          ownershipShare: 'Freehold 100%',
          registrationDate: '10.10.2022',
          encumbrance: 'Оформлено на офшорную компанию Solaris FZ',
        },
      ],
    },

    socialGraph: [
      {
        id: 'rel-01',
        relation: 'Отец',
        fio: 'Морозов Дмитрий Викторович',
        birthDate: '03.02.1962',
        phone: '+7 (916) 304-11-82',
        inn: '771004928104',
        notes: 'Бывший зам. руководителя департамента Минпромторга, пенсионер.',
        riskScore: 35,
      },
      {
        id: 'rel-02',
        relation: 'Мать',
        fio: 'Морозова (Волкова) Елена Сергеевна',
        birthDate: '19.11.1965',
        phone: '+7 (903) 140-92-33',
        inn: '771018492019',
        notes: 'Владелец сети арт-галерей на Патриарших.',
        riskScore: 20,
      },
      {
        id: 'rel-03',
        relation: 'Супруга',
        fio: 'Морозова (Калинина) Кристина Игоревна',
        birthDate: '25.07.1994',
        phone: '+7 (999) 812-44-00',
        inn: '772591048291',
        notes: 'Инфлюенсер, владелица бьюти-бренда в Дубае и Москве.',
        riskScore: 42,
      },
      {
        id: 'rel-04',
        relation: 'Бизнес-партнер / Теневой юрист',
        fio: 'Громов Кирилл Вадимович',
        birthDate: '08.06.1987',
        phone: '+7 (925) 441-09-11',
        inn: '770481920491',
        notes: 'Управляющий оффшорными трастами на Сейшелах и Кипре.',
        riskScore: 94,
      },
      {
        id: 'rel-05',
        relation: 'Доверенное лицо / Личный водитель-телохранитель',
        fio: 'Багиров Руслан Шамильевич',
        birthDate: '14.04.1988',
        phone: '+7 (968) 512-90-88',
        inn: '502481902834',
        notes: 'Разрешение на ношение служебного оружия ИЖ-71, ЧОП «Щит-Альфа».',
        riskScore: 78,
      },
    ],

    breaches: [
      {
        source: 'Яндекс.Еда (Утечка 2022)',
        date: '01.03.2022',
        leakedData: {
          address: 'г. Москва, ул. Тверская, д. 19, кв. 84, код домофона 84К4920',
          phone: '+79268401922',
          email: 'shadow_wolf89@protonmail.com',
          amountSpent: '₽ 1,480,200 за 2 года',
          notes: 'Оставлять у консьержа на 1 этаже. Не звонить в дверь, спит ребенок.',
          deviceInfo: 'iOS 15.3.1 (iPhone14,2)',
        },
        severity: 'CRITICAL',
      },
      {
        source: 'СДЭК Доставки (Утечка 2023)',
        date: '15.07.2023',
        leakedData: {
          address: 'Московская обл., Одинцовский р-н, пос. Барвиха, Сады Майендорф, уч. 14',
          phone: '+79268401922',
          email: 'morozov.capital@gmail.com',
          notes: 'Доставка ценного груза (электроника Ledger Nano X, 10 шт)',
        },
        severity: 'HIGH',
      },
      {
        source: 'Альфа-Банк Клиенты (Darknet Dump 2024)',
        date: '19.04.2024',
        leakedData: {
          phone: '+79268401922',
          email: 'a.morozov@solaris-capital.io',
          passwordHash: '$2a$12$e8Kz1V4n9LmPxQ90JmK0ueA8sKj39...',
          clearPassword: 'M0rozov_Capital#2024!',
          notes: 'VIP сегмент А-Клуб, персональный менеджер Баранова В.',
        },
        severity: 'CRITICAL',
      },
      {
        source: 'Гемотест / Invitro База пациентов (2022-2024)',
        date: '11.02.2024',
        leakedData: {
          phone: '+79268401922',
          notes: 'Группа крови AB (IV) Rh+, регулярные чекапы спортивной биохимии',
        },
        severity: 'MEDIUM',
      },
    ],

    geoHistory: [
      {
        id: 'geo-01',
        date: '20.09.2026',
        time: '01:15',
        locationName: 'Dubai Marina, Penthouse #8204',
        coordinates: [25.0805, 55.1403],
        category: 'Дом',
        source: 'Биллинг БС',
        details: 'Подключение к вышке Etisalat DXB-Cell-491',
      },
      {
        id: 'geo-02',
        date: '18.09.2026',
        time: '18:45',
        locationName: 'Международный аэропорт Дубай (DXB)',
        coordinates: [25.2532, 55.3657],
        category: 'Аэропорт',
        source: 'Авиаперелет',
        details: 'Рейс EK-132 Москва (DME) -> Дубай (DXB), Бизнес-класс 2A',
      },
      {
        id: 'geo-03',
        date: '18.09.2026',
        time: '11:30',
        locationName: 'Москва, Аэропорт Домодедово VIP Lounge',
        coordinates: [55.4088, 37.9063],
        category: 'Аэропорт',
        source: 'ФСБ Погранслужба',
        details: 'Прохождение пограничного контроля, загранпаспорт 75 №4820199',
      },
      {
        id: 'geo-04',
        date: '17.09.2026',
        time: '21:00',
        locationName: 'Москва, Ресторан «Сахалин», ул. Смоленская 8',
        coordinates: [55.7489, 37.5833],
        category: 'Ресторан/Клуб',
        source: 'Парковки Москвы',
        details: 'Оплата парковки а/м Porsche 911 (А777МР77) на 3.5 часа',
      },
      {
        id: 'geo-05',
        date: '16.09.2026',
        time: '14:20',
        locationName: 'КП «Сады Майендорф», Барвиха',
        coordinates: [55.7289, 37.2683],
        category: 'Дом',
        source: 'Яндекс.Еда',
        details: 'Доставка заказа из ресторана «Царская Охота» на сумму ₽ 18,400',
      },
    ],

    intelligenceNotes: {
      classification: 'СОВЕРШЕННО СЕКРЕТНО',
      cases: [
        'КУСП № 48192/24 — Проверка по факту вывода $14M через P2P шлюзы',
        'Материалы финмониторинга Росфинмониторинга № РФМ-8941-ОП',
        'Информатор в синдикате «Cyber Shaman Group»',
      ],
      vulnerabilities: [
        'Критическая зависимость от доступности дубайских счетов в Emirates NBD',
        'Часто использует один и тот же корневой пароль M0rozov_... в криптосервисах',
        'Регулярное посещение локаций в Барвихе без охраны по четвергам',
      ],
      psychologicalProfile: 'Высокий интеллект, выраженные лидерские качества, склонность к просчитанному риску. Крайне подозрителен к новым контактам. Применяет эшелонированную цифровую гигиену (Tails OS, GrapheneOS, аппаратные ключи YubiKey 5C).',
      lifestylePattern: 'Активный образ жизни, коллекционирование редких спорткаров, закрытые закрытые VIP-мероприятия в Дубае, Монако и на Патриарших.',
      surveillanceRecommended: true,
    },

    createdTimestamp: '20.09.2026 01:30:00 MSK',
  },

  {
    id: 'target-voronova-02',
    fio: {
      last: 'Воронова',
      first: 'Екатерина',
      middle: 'Сергеевна',
      full: 'Воронова Екатерина Сергеевна',
    },
    aliases: ['FireArrow', 'kate_voron', 'red_valkyrie', 'VoronovaInvest'],
    birthDate: '22.04.1993',
    birthPlace: 'г. Санкт-Петербург',
    age: 33,
    gender: 'Женский',
    zodiac: 'Телец ♉',
    totemAnimal: 'Ястреб',
    totemTitle: 'Огненная Стрела Небесного Дозора',
    threatLevel: 'HIGH',
    riskScore: 78,
    biometricMatchRate: 96.9,
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80',
    summary: 'Управляющая закрытым клубом частных инвесторов и элитных активов. Связана с трансграничными сделками по покупке недвижимости в ОАЭ, Турции и Швейцарии. Владеет сетью медиа-каналов.',

    documents: [
      {
        type: 'Паспорт гражданина РФ',
        series: '4013',
        number: '592011',
        issueDate: '10.05.2013',
        issuedBy: 'ТП № 25 ОУФМС России по Санкт-Петербургу',
        departmentCode: '780-025',
        status: 'Действителен',
        extra: {
          'Адрес регистрации': 'г. Санкт-Петербург, Крестовский остров, Морской пр-кт, д. 28, кв. 14',
          'СНИЛС': '142-901-839 44',
          'ИНН': '781309812401',
        },
      },
      {
        type: 'Заграничный паспорт РФ',
        series: '76',
        number: '9182340',
        issueDate: '04.09.2023',
        status: 'Действителен',
        extra: {
          'Действует до': '04.09.2033',
          'Визы': 'UAE Golden Visa (10 лет), Schengen Multi (Италия)',
        },
      },
    ],

    telecom: [
      {
        number: '+7 (911) 920-44-11',
        operator: 'ПАО МТС',
        region: 'г. Санкт-Петербург и Ленобласть',
        imsi: '250019482019401',
        imei: '359401928401923 (iPhone 16 Pro Desert Titanium)',
        period: '2019 — 2026',
        status: 'Активен',
        tags: ['Катя Воронова Недвижка', 'Екатерина Инвест СПб', 'Kate Palm Jumeirah VIP'],
        messengerStatus: { telegram: true, whatsapp: true, signal: true },
      },
    ],

    telegram: {
      id: '891048201',
      username: 'kate_voron',
      firstName: 'Ekaterina',
      lastName: 'Voronova',
      phone: '+79119204411',
      bio: 'Private Wealth & Global Real Estate. Living between SPb & Dubai.',
      leakedMessagesCount: 1840,
      groups: ['SPb Golden Mile Owners', 'Dubai Palm Residence Exclusive', 'Russian Riviera Yachting'],
      lastSeen: 'Вчера в 22:15',
    },

    emails: ['voronova.wealth@gmail.com', 'kate@voron-holdings.ch', 'fire_arrow_93@proton.me'],

    socialLinks: [
      { platform: 'Telegram', url: 'https://t.me/kate_voron', username: '@kate_voron' },
      { platform: 'Instagram', url: 'https://instagram.com/kate_voronova_official', username: 'kate_voronova_official' },
    ],

    ipAddresses: [
      { ip: '82.145.221.14', isp: 'Sky Mobile Telephony', city: 'Saint Petersburg, RU', lastSeen: '19.09.2026 22:04' },
      { ip: '185.190.140.8', isp: 'ProtonVPN AG', city: 'Zurich, CH', lastSeen: '17.09.2026 10:11' },
    ],

    finances: {
      estimatedNetWorth: '₽ 490,000,000 (~$5.3M)',
      taxId: '781309812401',
      snils: '142-901-839 44',
      banks: [
        {
          bank: 'АО «Альфа-Банк» (А-Клуб)',
          accountMasked: '40817810****8102',
          currency: 'RUB',
          balanceEstimated: '₽ 48,000,000',
          openDate: '15.01.2018',
          status: 'Активен',
        },
        {
          bank: 'Mashreq Bank (UAE)',
          accountMasked: 'AE210330****4910',
          currency: 'USD',
          balanceEstimated: '$ 2,900,000',
          openDate: '03.04.2023',
          status: 'Активен',
        },
      ],
      crypto: [
        {
          network: 'Tether (USDT TRC20)',
          address: 'TN8xKmP99104819Klsdpq981048124Ksm20',
          balance: '840,000 USDT',
          totalTx: 940,
          lastActivity: '18.09.2026 19:40',
          riskCategory: 'Чистый',
        },
      ],
      companies: [
        {
          name: 'ООО «ВОРОН ИНВЕСТ ГРУПП»',
          inn: '7813481902',
          ogrn: '1217800491028',
          role: 'Генеральный директор',
          revenueYear: '₽ 92,000,000 / год',
          status: 'Действующее',
          registrationDate: '19.03.2021',
        },
      ],
    },

    assets: {
      vehicles: [
        {
          brandModel: 'Bentley Continental GT V8 Azure',
          plate: 'О007ОО98',
          vin: 'SCBBE63W4NC029481',
          year: 2023,
          color: 'Кембриджский зеленый / светлая кожа',
          stsNumber: '7829 481920',
          osagoNumber: 'ХХХ 0481920194 (РЕСО-Гарантия VIP)',
          finesCount: 3,
          finesSum: '₽ 3,000',
          registrationDate: '18.06.2023',
          status: 'В собственности',
        },
      ],
      realEstate: [
        {
          type: 'Квартира',
          address: 'г. Санкт-Петербург, Морской пр-кт, д. 28, ЖК «Крестовский De Luxe»',
          cadastralNumber: '78:32:0001094:812',
          areaSqMeters: 220.0,
          estimatedPrice: '₽ 165,000,000',
          ownershipShare: '1/1',
          registrationDate: '14.07.2020',
        },
        {
          type: 'Апартаменты',
          address: 'UAE, Dubai, Palm Jumeirah, Royal Atlantis Residences',
          cadastralNumber: 'DXB-PALM-ATL-912',
          areaSqMeters: 280.0,
          estimatedPrice: '$ 3,200,000',
          ownershipShare: '100%',
          registrationDate: '05.11.2023',
        },
      ],
    },

    socialGraph: [
      {
        id: 'rel-v1',
        relation: 'Отец',
        fio: 'Воронов Сергей Александрович',
        birthDate: '10.10.1960',
        phone: '+7 (921) 934-88-12',
        inn: '781300948102',
        notes: 'Профессор СПбГУ, доктор экономических наук.',
      },
      {
        id: 'rel-v2',
        relation: 'Бизнес-партнер',
        fio: 'Аль-Мактум Рашид (Представитель офиса)',
        birthDate: '15.03.1984',
        notes: 'Соинвестор в девелоперских фондах ОАЭ.',
      },
    ],

    breaches: [
      {
        source: 'Delivery Club (Утечка 2022)',
        date: '20.05.2022',
        leakedData: {
          address: 'г. Санкт-Петербург, Морской пр-кт, 28, кв. 14',
          phone: '+79119204411',
          email: 'voronova.wealth@gmail.com',
          amountSpent: '₽ 680,000',
        },
        severity: 'HIGH',
      },
      {
        source: 'CDEK (Утечка 2023)',
        date: '12.08.2023',
        leakedData: {
          phone: '+79119204411',
          notes: 'Доставка ювелирных изделий Cartier, страховка ₽ 2,500,000',
        },
        severity: 'MEDIUM',
      },
    ],

    geoHistory: [
      {
        id: 'geo-v1',
        date: '19.09.2026',
        time: '20:15',
        locationName: 'СПб, Ресторан Il Lago dei Cigni, Крестовский остров',
        coordinates: [59.9764, 30.2443],
        category: 'Ресторан/Клуб',
        source: 'Парковки Москвы',
        details: 'Автомобиль Bentley Azure (О007ОО98)',
      },
    ],

    intelligenceNotes: {
      classification: 'ДСП',
      cases: ['Учет в управлении по валютному контролю Северо-Западного округа'],
      vulnerabilities: ['Постоянное пребывание в публичном пространстве, медийные риски'],
      psychologicalProfile: 'Уверенная, прагматичная, выстраивает устойчивые связи с высшими эшелонами бизнеса.',
      lifestylePattern: 'Гастрономические туры, яхтенный спорт, аукционы Sotheby’s.',
      surveillanceRecommended: false,
    },

    createdTimestamp: '20.09.2026 01:30:00 MSK',
  },

  {
    id: 'target-kovalev-03',
    fio: {
      last: 'Ковалев',
      first: 'Ярослав',
      middle: 'Игоревич',
      full: 'Ковалев Ярослав Игоревич',
    },
    aliases: ['Thunderbird', 'null_pointer', 'sec_arch', '0xKovalev'],
    birthDate: '07.11.1985',
    birthPlace: 'г. Новосибирск (Академгородок)',
    age: 40,
    gender: 'Мужской',
    zodiac: 'Скорпион ♏',
    totemAnimal: 'Громовая Птица',
    totemTitle: 'Громовая Птица Кибер-Шторма',
    threatLevel: 'CRITICAL',
    riskScore: 95,
    biometricMatchRate: 99.1,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    summary: 'Эксперт высшей категории по кибер-разведке (OSINT/HUMINT), криптографии и пентестингу критической инфраструктуры. Основатель закрытого синдиката информационной безопасности.',

    documents: [
      {
        type: 'Паспорт гражданина РФ',
        series: '5005',
        number: '194012',
        issueDate: '12.11.2005',
        issuedBy: 'Советский РУВД г. Новосибирска',
        departmentCode: '540-008',
        status: 'Действителен',
      },
    ],

    telecom: [
      {
        number: '+7 (999) 001-33-77',
        operator: 'ПАО МегаФон',
        region: 'г. Москва',
        imsi: '250020109284109',
        imei: '864910294019284 (Purism Librem 5 / PureOS)',
        period: '2020 — 2026',
        status: 'Активен',
        tags: ['Ярослав Sec', 'Thunderbird Dev', '0xKovalev'],
        messengerStatus: { telegram: true, signal: true },
      },
    ],

    telegram: {
      id: '13370042',
      username: 'null_pointer_arch',
      firstName: 'Jaroslav',
      lastName: 'K.',
      bio: 'Cryptographic architectures & zero-knowledge proofs. PGP in bio.',
      leakedMessagesCount: 9400,
      groups: ['Chaos Computer Club Mirror', 'Red Teaming Elite CIS', '0day Exploit Exchange'],
    },

    emails: ['kovalev@cyber-totem.net', 'thunderbird@cock.li (PGP Verified)', 'null@0xsec.io'],
    socialLinks: [
      { platform: 'GitHub', url: 'https://github.com/0x-thunderbird', username: '0x-thunderbird' },
      { platform: 'Keybase', url: 'https://keybase.io/jaroslav_kovalev', username: 'jaroslav_kovalev' },
    ],

    ipAddresses: [
      { ip: '194.26.29.112', isp: 'Mullvad VPN / WireGuard', city: 'Stockholm, SE', lastSeen: '20.09.2026 01:28' },
    ],

    finances: {
      estimatedNetWorth: '₽ 620,000,000 (~$6.8M в криптоактивах)',
      taxId: '540891048201',
      snils: '130-948-291 00',
      banks: [
        {
          bank: 'АО «Райффайзенбанк» Премиум',
          accountMasked: '40817810****3019',
          currency: 'RUB / EUR',
          balanceEstimated: '₽ 21,000,000',
          openDate: '10.08.2015',
          status: 'Активен',
        },
      ],
      crypto: [
        {
          network: 'Bitcoin (BTC)',
          address: 'bc1qthunderbird88941029410294k10294k1029k41',
          balance: '48.50 BTC',
          totalTx: 3820,
          lastActivity: '19.09.2026 23:59',
          riskCategory: 'Миксер/Darknet',
        },
        {
          network: 'Monero (XMR)',
          address: '888kovalevXMR9812498104829104812904812048...',
          balance: '1,850.0 XMR',
          totalTx: 940,
          lastActivity: '20.09.2026',
          riskCategory: 'Миксер/Darknet',
        },
      ],
      companies: [
        {
          name: 'ООО «СИБИРСКИЙ КИБЕР-ЩИТ»',
          inn: '5408481920',
          ogrn: '1175408019284',
          role: 'Учредитель (100%)',
          revenueYear: '₽ 110,000,000 / год',
          status: 'Действующее',
          registrationDate: '04.09.2017',
        },
      ],
    },

    assets: {
      vehicles: [
        {
          brandModel: 'BMW M5 CS (F90)',
          plate: 'Х001ХХ154',
          vin: 'WBA00000491029412',
          year: 2022,
          color: 'Frozen Deep Green Metallic',
          stsNumber: '5420 194820',
          osagoNumber: 'ХХХ 0948192049',
          finesCount: 22,
          finesSum: '₽ 44,000 (Оплачены)',
          registrationDate: '19.11.2022',
          status: 'В собственности',
        },
      ],
      realEstate: [
        {
          type: 'Загородный дом',
          address: 'г. Новосибирск, Академгородок, Золотодолинская ул., коттедж 18',
          cadastralNumber: '54:35:091402:194',
          areaSqMeters: 450.0,
          estimatedPrice: '₽ 85,000,000',
          ownershipShare: '1/1',
          registrationDate: '12.05.2019',
        },
      ],
    },

    socialGraph: [
      {
        id: 'rel-k1',
        relation: 'Брат',
        fio: 'Ковалев Денис Игоревич',
        birthDate: '18.09.1989',
        phone: '+7 (913) 481-00-22',
        notes: 'Senior DevOps инженер в крупном финтех-холдинге.',
      },
    ],

    breaches: [
      {
        source: 'BreachForums / 0day Leaks (2024)',
        date: '10.01.2024',
        leakedData: {
          email: 'null@0xsec.io',
          passwordHash: 'Argon2id$v=19$m=65536,t=3,p=4$... (Не взломан)',
          notes: 'Хэш устойчив к брутфорсу на GPU кластерах',
        },
        severity: 'MEDIUM',
      },
    ],

    geoHistory: [
      {
        id: 'geo-k1',
        date: '20.09.2026',
        time: '01:00',
        locationName: 'Новосибирск, Академгородок, Золотодолинская 18',
        coordinates: [54.8488, 83.1054],
        category: 'Дом',
        source: 'Биллинг БС',
        details: 'Автономный серверный дата-центр',
      },
    ],

    intelligenceNotes: {
      classification: 'СОВЕРШЕННО СЕКРЕТНО',
      cases: ['Экспертное заключение по защите критических узлов РЖД и Ростелеком'],
      vulnerabilities: ['Чрезмерная самоуверенность в программно-аппаратных криптографических модулях'],
      psychologicalProfile: 'Интроверт, аналитический склад ума, феноменальная память.',
      lifestylePattern: 'Работает преимущественно ночью, регулярные выезды на горнолыжные курорты Алтая и Шерегеша.',
      surveillanceRecommended: true,
    },

    createdTimestamp: '20.09.2026 01:30:00 MSK',
  },

  {
    id: 'target-zakharov-04',
    fio: {
      last: 'Захаров',
      first: 'Виктор',
      middle: 'Павлович',
      full: 'Захаров Виктор Павлович',
    },
    aliases: ['IronBison', 'vp_zakharov', 'BisonCapital', 'UralTitan'],
    birthDate: '03.05.1972',
    birthPlace: 'г. Екатеринбург (Свердловск)',
    age: 54,
    gender: 'Мужской',
    zodiac: 'Телец ♉',
    totemAnimal: 'Бизон',
    totemTitle: 'Железный Бизон Уральской Твердыни',
    threatLevel: 'ELEVATED',
    riskScore: 64,
    biometricMatchRate: 97.8,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    summary: 'Крупный промышленник, инвестор в горнорудные и логистические холдинги Урала и Сибири. Активный участник закрытых правительственных комиссий по развитию логистических коридоров.',

    documents: [
      {
        type: 'Паспорт гражданина РФ',
        series: '6502',
        number: '771920',
        issueDate: '15.05.2017',
        issuedBy: 'УФМС Верх-Исетского р-на Екатеринбурга',
        departmentCode: '660-001',
        status: 'Действителен',
        extra: {
          'СНИЛС': '110-829-301 88',
          'ИНН': '665801948201',
        },
      },
    ],

    telecom: [
      {
        number: '+7 (902) 870-00-01',
        operator: 'ПАО Мотив / МТС',
        region: 'Свердловская область',
        imsi: '250359182049102',
        imei: '358102948102938 (Caviar Gold iPhone 15 Pro Custom)',
        period: '2015 — 2026',
        status: 'Активен',
        tags: ['Захаров В.П. Мотив VIP', 'Виктор Павлович Шеф', 'Захаров Титан Холдинг'],
        messengerStatus: { telegram: true, whatsapp: true },
      },
    ],

    telegram: {
      id: '77719201',
      username: 'vp_zakharov_official',
      firstName: 'Виктор',
      lastName: 'Захаров',
      phone: '+79028700001',
      bio: 'Промышленность, инвестиции, инфраструктурные проекты.',
      leakedMessagesCount: 890,
      groups: ['Уральский Союз Промышленников VIP', 'Бизнес-Авиация Кольцово'],
    },

    emails: ['zakharov@uraltitan-holding.ru', 'vp_secretariat@zakharov.group'],
    socialLinks: [
      { platform: 'РБК Профиль', url: 'https://rbc.ru/persons/zakharov_vp', username: 'Захаров Виктор' },
    ],

    ipAddresses: [
      { ip: '89.111.45.19', isp: 'Планета / Квант (Екатеринбург)', city: 'Екатеринбург, RU', lastSeen: '19.09.2026 19:30' },
    ],

    finances: {
      estimatedNetWorth: '₽ 2,450,000,000 (~$26.9M)',
      taxId: '665801948201',
      snils: '110-829-301 88',
      banks: [
        {
          bank: 'Банк ВТБ (ПАО) Private Banking',
          accountMasked: '40817810****7701',
          currency: 'RUB',
          balanceEstimated: '₽ 410,000,000',
          openDate: '20.03.2012',
          status: 'Активен',
        },
        {
          bank: 'Газпромбанк (АО) VIP',
          accountMasked: '40817810****1920',
          currency: 'RUB / CNY',
          balanceEstimated: '¥ 18,500,000',
          openDate: '11.08.2022',
          status: 'Активен',
        },
      ],
      crypto: [],
      companies: [
        {
          name: 'ПАО «УРАЛТИТАН ХОЛДИНГ»',
          inn: '6658491028',
          ogrn: '1026605294819',
          role: 'Бенефициарный владелец',
          revenueYear: '₽ 4,120,000,000 / год',
          status: 'Действующее',
          registrationDate: '15.11.2002',
        },
      ],
    },

    assets: {
      vehicles: [
        {
          brandModel: 'Rolls-Royce Cullinan Black Badge',
          plate: 'А001АА66',
          vin: 'SCA684K08NU019481',
          year: 2022,
          color: 'Black Diamond',
          stsNumber: '6620 481920',
          osagoNumber: 'ХХХ 0192840192',
          finesCount: 8,
          finesSum: '₽ 12,000 (Оплачены)',
          registrationDate: '24.08.2022',
          status: 'В собственности',
        },
      ],
      realEstate: [
        {
          type: 'Загородный дом',
          address: 'Свердловская обл., Сысертский р-н, пос. Карасьеозерский-1, ул. Лесная 7',
          cadastralNumber: '66:25:0104819:104',
          areaSqMeters: 1200.0,
          estimatedPrice: '₽ 320,000,000',
          ownershipShare: '1/1',
          registrationDate: '19.04.2016',
        },
      ],
    },

    socialGraph: [
      {
        id: 'rel-z1',
        relation: 'Сын',
        fio: 'Захаров Павел Викторович',
        birthDate: '14.06.1998',
        phone: '+7 (912) 201-94-11',
        inn: '665891048291',
        notes: 'Член совета директоров ПАО «Уралтитан Холдинг».',
      },
    ],

    breaches: [
      {
        source: 'СДЭК VIP Клиенты (2023)',
        date: '04.04.2023',
        leakedData: {
          address: 'г. Екатеринбург, Карасьеозерский-1, Лесная 7',
          phone: '+79028700001',
          notes: 'Конфиденциальная доставка документов',
        },
        severity: 'MEDIUM',
      },
    ],

    geoHistory: [
      {
        id: 'geo-z1',
        date: '19.09.2026',
        time: '17:00',
        locationName: 'Екатеринбург, Аэропорт Кольцово VIP Терминал',
        coordinates: [56.7431, 60.8037],
        category: 'Аэропорт',
        source: 'Авиаперелет',
        details: 'Бизнес-джет Challenger 850 (RA-67219) рейс Екатеринбург -> Москва',
      },
    ],

    intelligenceNotes: {
      classification: 'ОПЕРАТИВНЫЙ УЧЕТ',
      cases: ['Участие в приватизационных аукционах 2000-х годов'],
      vulnerabilities: ['Повышенное внимание СМИ к экологическим проверкам предприятий'],
      psychologicalProfile: 'Консервативный, жесткий переговорщик, чтит строгую субординацию.',
      lifestylePattern: 'Охота на Алтае, коллекционирование редкого холодного оружия.',
      surveillanceRecommended: false,
    },

    createdTimestamp: '20.09.2026 01:30:00 MSK',
  },
];
